version: "3.8"
volumes:
  postgres_data:
  valkey_data:
    driver: local

services:
  db:
    container_name: ${PROJECT_NAME:-default}-postgresdb
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGPASSWORD: ${PGPASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    container_name: ${PROJECT_NAME:-default}-valkey_server
    image: docker.io/bitnami/valkey:8.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'valkey_data:/bitnami/valkey/data'
    depends_on:
      - db
  zipkin:
    image: openzipkin/zipkin
    container_name: ${PROJECT_NAME:-default}-zipkin
    ports:
      - "9411:9411"
    depends_on:
      - service-registry

  service-registry:
    container_name: ${PROJECT_NAME:-default}-service-registry
    build:
      context: ../service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  api-gateway:
    container_name: ${PROJECT_NAME:-default}-api-gateway
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - service-registry
  app:
    container_name: ${PROJECT_NAME:-default}-javadev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOSTNAME: postgres
    ports:
      - "8080:8080"
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - service-registry
      - db
      - valkey
      - zipkin
    command: sleep infinity
