server:
  shutdown: graceful
  port: 8080
spring:
  application:
    name: backend
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SYSTEM_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000                  # Default: 30000 (30 seconds)
      minimum-idle: 2                            # Default: same as maximumPoolSize
      maximum-pool-size: 10
  flyway:
    enabled: false
    outOfOrder: true
    locations: classpath:db/migration, classpath:db/migration_local
    baseline-on-migrate: true
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}


  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: warn
    web: info
    org.zalando.logbook: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.SQL: DEBUG

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka