server:
  shutdown: graceful
  port: 8080
spring:
  application:
    name: backend
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SYSTEM_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000                  # Default: 30000 (30 seconds)
      minimum-idle: 2                            # Default: same as maximumPoolSize
      maximum-pool-size: 10
  flyway:
    enabled: true
    outOfOrder: true
    locations: classpath:db/migration, classpath:db/migration_local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #  jpa:
  #    open-in-view: false
  #    show-sql: true
  #    defer-datasource-initialization: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    root: warn
    web: info
